KNOWN_ARTISTS = [
    "3Y Gun Kara",
    "Adma",
    "Alberto",
    "Alcomindz Mafia",
    "Aleshen",
    "Asster",
    "Avi",
    "Bambi",
    "Bas Tajpan",
    "Bedoes 2115",
    "Belmondo",
    "Beodes 2115",
    "Beteo",
    "Bezczel",
    "Białas",
    "Blacha 2115",
    "Bober",
    "Bonson",
    "Bonus Rpk",
    "Borixon",
    "Chada",
    "Deys",
    "Diho",
    "Dixon37",
    "Donguralesko",
    "Dudek P56",
    "Dwa Slawy",
    "Eis",
    "Eldo",
    "Ero",
    "Ero Jwp",
    "Fagata",
    "Filipek",
    "Firma",
    "Fisz",
    "Frosti",
    "Gang Albanii",
    "Gedz",
    "Grammatik",
    "Grubson",
    "Gruby Mielzky",
    "Guzior",
    "Hades",
    "Jan Rapowanie",
    "Janusz Walczuk",
    "Jedker",
    "Jetlagz",
    "Jongmen",
    "Josef Bratan",
    "Jwp",
    "Kabe",
    "Kacper Hta",
    "Kaen",
    "Kali",
    "Kartky",
    "Kaz Balagane",
    "Kiełas",
    "Kizo",
    "Kuban",
    "Kukon",
    "Kękę",
    "Leh",
    "Liroy",
    "Malik Montana",
    "Malolat",
    "Mata",
    "Małpa",
    "Miy Atz",
    "Mobbyn",
    "Numer Raz",
    "Og Kamka",
    "Oki",
    "Onar",
    "Ostr",
    "Otsochodzi",
    "Paktofonika",
    "Paluch",
    "Peja",
    "Pelson",
    "Pezet",
    "Pih",
    "Pikers",
    "Pokahontaz",
    "Pono",
    "Popek",
    "Pro8L3M",
    "Quebonafide",
    "Rogal Ddl",
    "Sarius",
    "Schafter",
    "Sentino",
    "Slon",
    "Slowez",
    "Sobota",
    "Sokół",
    "Szpaku",
    "Szymi Szyms",
    "Taco Hemingway",
    "Taconafide",
    "Te Tris",
    "Tede",
    "Ten Typ Mes",
    "Undadasea",
    "Vkie",
    "Wdowa",
    "White 2115",
    "Wini",
    "Wwo",
    "Young Igi",
    "Young Leosia",
    "Young Multi",
    "Yung Adisz",
    "Zbuku",
    "Zeamsone",
    "Zip Skład",
    "Zuziula",
    "Łona",
    "Łona I Webber",
    "Żabson",
]
